builds:
  - id: "timeout-checker"
    main: ./
    binary: checker-api
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    goarm:
      - "8"
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - id: golang-cross
    builds:
      - "timeout-checker"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: "true"
    files:
    - "echo.json"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    tap:
      owner: applegreengrape
      name: timeout-checker
    folder: Formula
    homepage: https://github.com/applegreengrape/timeout-checker
    description: simple wait& response api for timeout test
dockers:
  - image_templates:
    - "ghcr.io/billglover/{{ .ProjectName }}:{{ .Version }}-amd64"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/billglover/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/billglover/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    extra_files:
      - "echo.json"
  - image_templates:
    - "ghcr.io/billglover/{{ .ProjectName }}:{{ .Version }}-arm64"
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/arm64/v8
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/billglover/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/billglover/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    extra_files:
      - "echo.json"
docker_manifests:
- name_template: ghcr.io/billglover/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/billglover/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/billglover/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/billglover/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/billglover/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/billglover/{{ .ProjectName }}:{{ .Version }}-arm64v8